<div id = "uploadBox">
	<div class = "subtitle">Upload Data</div>
	<input id = "uploadCSV" type="button" value="Upload CSV"/>
	<div class = "subtitle">Visualize Data</div>
	<select id = "seriesSelect">
		<option value="">*select</option>
		<option value="precipitation">Precipitation</option>
		<option value="days">Heat/Cooling days</option>
		<option value="temperature">Temperature</option>
	</select>
	
	<div id = "fileInputContainer"><input name = "dataUploadInput" type="file" accept="text/csv"/></div>
	<div id = "chartRegion"></div>
	<div id = "slider1"></div>
	<div id = "slider2"></div>
</div>
<div id = "logoutContainer">
	<a href="../">Logout</a>
</div>