<!DOCTYPE html>
<html>
<head>
<?php 
	include("head.phtml"); 
	$data = new Data();
	$data->getUserData(1);
?>
</head>
<body>
	<div class = "verticalCenter"></div>
	<div id = "pageContainer">
		<div id = "title">Climate<b>View</b></div>
		
		<!-- Login Section -->
		<?php include("loginBox.phtml"); ?>
		
		<!-- Upload Data Section -->
		<?php include("dataBox.phtml"); ?>
	</div>
	<video autoplay loop>
		<source src="/images/clouds.mp4" type="video/mp4">
	</video>
</body>
</html>